name: jeffsimeon
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7546826156321913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.014121525222435594
  saturation: 0.049971406580880284
  rhythmicContrast: 0.6641567428596318
purpose: []
